import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { mkdirSync } from 'node:fs';

const args = process.argv.slice(2);
const writeIndex = args.indexOf('--write');
const shouldWrite = writeIndex >= 0;
const check = args.includes('--check');
const outputPath = shouldWrite ? resolve(args[writeIndex + 1] || 'apps/api/d1/seed.sql') : resolve('apps/api/d1/seed.sql');
const seedPath = resolve('apps/api/data/seed.json');
const seed = JSON.parse(readFileSync(seedPath, 'utf8'));
const output = [
  '-- Generated by scripts/export-d1-seed.mjs from apps/api/data/seed.json.',
  '-- Safe to re-run; it only inserts app_state when the default row does not exist.',
  `insert or ignore into app_state (id, payload, updated_at) values ('default', ${sql(JSON.stringify(seed))}, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));`,
  '',
].join('\n');

if (check) {
  if (!existsSync(outputPath)) {
    console.error(JSON.stringify({ ok: false, error: 'missing_d1_seed', outputPath }, null, 2));
    process.exit(1);
  }
  const existing = readFileSync(outputPath, 'utf8');
  if (existing !== output) {
    console.error(JSON.stringify({ ok: false, error: 'd1_seed_out_of_date', outputPath }, null, 2));
    process.exit(1);
  }
}

if (shouldWrite) {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, output);
}

console.log(
  JSON.stringify(
    {
      ok: true,
      seedPath,
      outputPath: shouldWrite || check ? outputPath : null,
      mode: check ? 'check' : shouldWrite ? 'write' : 'stdout',
      bytes: Buffer.byteLength(output),
      sha256: createHash('sha256').update(output).digest('hex'),
    },
    null,
    2,
  ),
);

if (!shouldWrite && !check) process.stdout.write(output);

function sql(value) {
  return `'${String(value ?? '').replaceAll("'", "''")}'`;
}
